
export const publicRoutes = [
  { value: '/', label: 'Home' },
  { value: '/about-us', label: 'About Us' },
  { value: '/account', label: 'Account' },
  { value: '/become-a-vendor', label: 'Become a Vendor' },
  { value: '/cookies-policy', label: 'Cookies Policy' },
  { value: '/fees', label: 'Fees' },
  { value: '/health', label: 'Health' },
  { value: '/help', label: 'Help' },
  { value: '/imprint', label: 'Imprint' },
  { value: '/kyc', label: 'Kyc' },
  { value: '/my-offers', label: 'My Offers' },
  { value: '/offer', label: 'Offer' },
  { value: '/privacy-policy', label: 'Privacy Policy' },
  { value: '/terms-and-conditions', label: 'Terms and Conditions' },
  { value: '/tier', label: 'Tier' },
  { value: '/trade', label: 'Trade' },
  { value: '/trades', label: 'Trades' },
  { value: '/vendor', label: 'Vendor' },
  { value: '/vendors', label: 'Vendors' },
];

export const adminRoutes = [
  { value: '/account', label: 'Account' },
  { value: '/admins', label: 'Admins' },
  { value: '/analytics', label: 'Analytics' },
  { value: '/banners', label: 'Banners' },
  { value: '/chats', label: 'Chats' },
  { value: '/cryptocurrencies', label: 'Cryptocurrencies' },
  { value: '/dashboard', label: 'Dashboard' },
  { value: '/dispute', label: 'Dispute' },
  { value: '/disputes', label: 'Disputes' },
  { value: '/fiats', label: 'Fiats' },
  { value: '/kyc', label: 'Kyc' },
  { value: '/login', label: 'Login' },
  { value: '/offers', label: 'Offers' },
  { value: '/payment-method-categories', label: 'Payment Method Categories' },
  { value: '/payment-methods', label: 'Payment Methods' },
  { value: '/settings', label: 'Settings' },
  { value: '/smart-contracts', label: 'Smart Contracts' },
  { value: '/trade', label: 'Trade' },
  { value: '/trades', label: 'Trades' },
  { value: '/users', label: 'Users' },
];
