
export const publicRoutes = [
  { value: '/', label: 'Home' },
  { value: '/about-us', label: 'About Us' },
  { value: '/account', label: 'Account' },
  { value: '/account/kyc', label: 'Account KYC' },
  { value: '/account/messages', label: 'Account Messages' },
  { value: '/account/password/reset/[token]', label: 'Reset Password' },
  { value: '/account/payment-methods', label: 'Payment Methods' },
  { value: '/account/premium', label: 'Premium' },
  { value: '/account/rewards', label: 'Rewards' },
  { value: '/account/settings', label: 'Settings' },
  { value: '/account/settings/email/verify/[token]', label: 'Verify Email' },
  { value: '/account/verify/[token]', label: 'Verify Account' },
  { value: '/become-a-vendor', label: 'Become a Vendor' },
  { value: '/cookies-policy', label: 'Cookies Policy' },
  { value: '/fees', label: 'Fees' },
  { value: '/help', label: 'Help' },
  { value: '/imprint', label: 'Imprint' },
  { value: '/kyc', label: 'KYC' },
  { value: '/my-offers', label: 'My Offers' },
  { value: '/offer/create', label: 'Create Offer' },
  { value: '/offer/[id]', label: 'View Offer' },
  { value: '/offer/[id]/edit', label: 'Edit Offer' },
  { value: '/privacy-policy', label: 'Privacy Policy' },
  { value: '/terms-and-conditions', label: 'Terms and Conditions' },
  { value: '/tier', label: 'Tier' },
  { value: '/trade/[id]', label: 'View Trade' },
  { value: '/trade/[id]/details', label: 'Trade Details' },
  { value: '/trade/[id]/vendor', label: 'Trade Vendor' },
  { value: '/trades', label: 'Trades' },
  { value: '/vendor/[id]', label: 'View Vendor' },
  { value: '/vendors', label: 'Vendors' },
];

export const adminRoutes = [
  { value: '/', label: 'Home' },
  { value: '/account/password/set/[token]', label: 'Set Password' },
  { value: '/admins', label: 'Admins' },
  { value: '/analytics', label: 'Analytics' },
  { value: '/banners', label: 'Banners' },
  { value: '/banners/create', label: 'Create Banner' },
  { value: '/banners/edit/[id]', label: 'Edit Banner' },
  { value: '/chats', label: 'Chats' },
  { value: '/cryptocurrencies', label: 'Cryptocurrencies' },
  { value: '/cryptocurrencies/create', label: 'Create Cryptocurrency' },
  { value: '/dashboard', label: 'Dashboard' },
  { value: '/dispute/[id]', label: 'View Dispute' },
  { value: '/disputes', label: 'Disputes' },
  { value: '/fiats', label: 'Fiats' },
  { value: '/fiats/create', label: 'Create Fiat' },
  { value: '/kyc', label: 'KYC' },
  { value: '/kyc/[id]', label: 'View KYC' },
  { value: '/login', label: 'Login' },
  { value: '/offers', label: 'Offers' },
  { value: '/payment-method-categories', label: 'Payment Method Categories' },
  { value: '/payment-method-categories/create', label: 'Create Payment Method Category' },
  { value: '/payment-methods', label: 'Payment Methods' },
  { value: '/payment-methods/create', label: 'Create Payment Method' },
  { value: '/settings', label: 'Settings' },
  { value: '/smart-contracts', label: 'Smart Contracts' },
  { value: '/smart-contracts/deploy', label: 'Deploy Smart Contract' },
  { value: '/trade/[id]/dispute', label: 'Dispute Trade' },
  { value: '/trades', label: 'Trades' },
  { value: '/users', label: 'Users' },
  { value: '/users/create', label: 'Create User' },
  { value: '/wallets', label: 'Wallets' },
];
