import {
  Australia,
  Brazil,
  Canada,
  China,
  Czechia,
  Denmark,
  Europe,
  HongKong,
  India,
  Indonesia,
  Israel,
  Japan,
  Malaysia,
  Mexico,
  NewZealand,
  Norway,
  Philippines,
  Poland,
  SaudiArabia,
  Singapore,
  SouthAfrica,
  SouthKorea,
  Sweden,
  Switzerland,
  Thailand,
  Turkey,
  Ukraine,
  UnitedArabEmirates,
  UnitedKingdom,
  UnitedStates,
} from '@/assets';

const countryFlags: { [key: string]: string } = {
  'united states': UnitedStates.src,
  'european union': Europe.src,
  japan: Japan.src,
  'united kingdom': UnitedKingdom.src,
  china: China.src,
  switzerland: Switzerland.src,
  canada: Canada.src,
  australia: Australia.src,
  'hong kong': HongKong.src,
  'new zealand': NewZealand.src,
  sweden: Sweden.src,
  'south korea': SouthKorea.src,
  singapore: Singapore.src,
  norway: Norway.src,
  india: India.src,
  mexico: Mexico.src,
  'south africa': SouthAfrica.src,
  turkey: Turkey.src,
  brazil: Brazil.src,
  'saudi arabia': SaudiArabia.src,
  'united arab emirates': UnitedArabEmirates.src,
  thailand: Thailand.src,
  malaysia: Malaysia.src,
  poland: Poland.src,
  denmark: Denmark.src,
  indonesia: Indonesia.src,
  israel: Israel.src,
  philippines: Philippines.src,
  'czech republic': Czechia.src,
  ukraine: Ukraine.src,
};

export default countryFlags;
