export const countries = [
  'Afghanistan',
  'Albania',
  'Algeria',
  'Andorra',
  'Angola',
  'Antigua and Barbuda',
  'Argentina',
  'Armenia',
  'Australia',
  'Austria',
  'Azerbaijan',
  'Bahamas',
  'Bahrain',
  'Bangladesh',
  'Barbados',
  'Belarus',
  'Belgium',
  'Belize',
  'Benin',
  'Bhutan',
  'Bolivia',
  'Bosnia and Herzegovina',
  'Botswana',
  'Brazil',
  'Brunei',
  'Bulgaria',
  'Burkina Faso',
  'Burundi',
  'Cambodia',
  'Cameroon',
  'Canada',
  'Cape Verde',
  'Central African Republic',
  'Chad',
  'Chile',
  'China',
  'Colombia',
  'Comoros',
  'Congo (Republic of)',
  'Congo (Democratic Republic of the)',
  'Costa Rica',
  "Côte d'Ivoire",
  'Croatia',
  'Cuba',
  'Cyprus',
  'Czech Republic',
  'Denmark',
  'Djibouti',
  'Dominica',
  'Dominican Republic',
  'Ecuador',
  'Egypt',
  'El Salvador',
  'Equatorial Guinea',
  'Eritrea',
  'Estonia',
  'Eswatini',
  'Ethiopia',
  'Fiji',
  'Finland',
  'France',
  'Gabon',
  'Gambia',
  'Georgia',
  'Germany',
  'Ghana',
  'Greece',
  'Grenada',
  'Guatemala',
  'Guinea',
  'Guinea-Bissau',
  'Guyana',
  'Haiti',
  'Honduras',
  'Hungary',
  'Iceland',
  'India',
  'Indonesia',
  'Iran',
  'Iraq',
  'Ireland',
  'Israel',
  'Italy',
  'Jamaica',
  'Japan',
  'Jordan',
  'Kazakhstan',
  'Kenya',
  'Kiribati',
  'Kuwait',
  'Kyrgyzstan',
  'Laos',
  'Latvia',
  'Lebanon',
  'Lesotho',
  'Liberia',
  'Libya',
  'Liechtenstein',
  'Lithuania',
  'Luxembourg',
  'Madagascar',
  'Malawi',
  'Malaysia',
  'Maldives',
  'Mali',
  'Malta',
  'Marshall Islands',
  'Mauritania',
  'Mauritius',
  'Mexico',
  'Micronesia',
  'Moldova',
  'Monaco',
  'Mongolia',
  'Montenegro',
  'Morocco',
  'Mozambique',
  'Myanmar',
  'Namibia',
  'Nauru',
  'Nepal',
  'Netherlands',
  'New Zealand',
  'Nicaragua',
  'Niger',
  'Nigeria',
  'North Korea',
  'North Macedonia',
  'Norway',
  'Oman',
  'Pakistan',
  'Palau',
  'Panama',
  'Papua New Guinea',
  'Paraguay',
  'Peru',
  'Philippines',
  'Poland',
  'Portugal',
  'Qatar',
  'Romania',
  'Russia',
  'Rwanda',
  'Saint Kitts and Nevis',
  'Saint Lucia',
  'Saint Vincent and the Grenadines',
  'Samoa',
  'San Marino',
  'São Tomé and Príncipe',
  'Saudi Arabia',
  'Senegal',
  'Serbia',
  'Seychelles',
  'Sierra Leone',
  'Singapore',
  'Slovakia',
  'Slovenia',
  'Solomon Islands',
  'Somalia',
  'South Africa',
  'South Korea',
  'South Sudan',
  'Spain',
  'Sri Lanka',
  'Sudan',
  'Suriname',
  'Sweden',
  'Switzerland',
  'Syria',
  'Tajikistan',
  'Tanzania',
  'Thailand',
  'Timor-Leste',
  'Togo',
  'Tonga',
  'Trinidad and Tobago',
  'Tunisia',
  'Turkey',
  'Turkmenistan',
  'Tuvalu',
  'Uganda',
  'Ukraine',
  'United Arab Emirates',
  'United Kingdom',
  'United States',
  'Uruguay',
  'Uzbekistan',
  'Vanuatu',
  'Venezuela',
  'Vietnam',
  'Yemen',
  'Zambia',
  'Zimbabwe',
];

export const documentTypes = [
  { label: 'Alien Registration Card', value: 'ALIEN_REGISTRATION_CARD' },
  { label: 'Citizenship Certificate', value: 'CITIZENSHIP_CERTIFICATE' },
  { label: 'Consular ID Card', value: 'CONSULAR_ID_CARD' },
  { label: "Driver's License", value: 'DRIVERS_LICENSE' },
  { label: 'Firearms License', value: 'FIREARMS_LICENSE' },
  { label: 'Government-Issued ID Card', value: 'GOVERNMENT_ISSUED_ID_CARD' },
  { label: 'Health Insurance Card', value: 'HEALTH_INSURANCE_CARD' },
  { label: 'Immigration Document', value: 'IMMIGRATION_DOCUMENT' },
  {
    label: 'Income Tax Identification Document',
    value: 'INCOME_TAX_IDENTIFICATION_DOCUMENT',
  },
  { label: 'Military ID', value: 'MILITARY_ID' },
  { label: 'National ID Card', value: 'NATIONAL_ID_CARD' },
  { label: 'Passport', value: 'PASSPORT' },
  { label: 'Permanent Resident Card', value: 'PERMANENT_RESIDENT_CARD' },
  { label: 'Refugee Travel Document', value: 'REFUGEE_TRAVEL_DOCUMENT' },
  { label: 'Residence Permit', value: 'RESIDENCE_PERMIT' },
  { label: 'Social Security Card', value: 'SOCIAL_SECURITY_CARD' },
  { label: 'Tax Identification Card', value: 'TAX_IDENTIFICATION_CARD' },
  { label: 'Voter ID Card', value: 'VOTER_ID_CARD' },
  { label: 'Work Permit', value: 'WORK_PERMIT' },
];

export const documentTypesWithBack = [
  'ALIEN_REGISTRATION_CARD',
  'DRIVERS_LICENSE',
  'GOVERNMENT_ISSUED_ID_CARD',
  'HEALTH_INSURANCE_CARD',
  'MILITARY_ID',
  'NATIONAL_ID_CARD',
  'PERMANENT_RESIDENT_CARD',
  'RESIDENCE_PERMIT',
  'VOTER_ID_CARD',
];
